version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - 9090:9090  
  nodeapp:
    image: node:lts-slim
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - METRICS_EXPIRATION_CHECK=5 # In seconds
      - METRICS_EXPIRATION=30 #In seconds
      - ALLOW_PRIVATE_SCRAPE_ONLY=true
      - PUSH_URL=http://127.0.0.1:3000/metrics/push # the push url that will be used by users
    networks:
      - localprom
    volumes:
      - .:/nodeapp
    ports:
      - 3000:3000
    working_dir: /nodeapp
    command: npm start
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - localprom
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3001:3000'
    networks:
      - localprom
      
networks:
  localprom:
    driver: bridge