services:
  jcmc:
    image: jcmc
    build:
      context: .
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - METRICS_EXPIRATION_CHECK=5 # In seconds
      - METRICS_EXPIRATION=30 #In seconds
      - ALLOW_PRIVATE_SCRAPE_ONLY=false
      - PUSH_URL=http://127.0.0.1:3000/metrics/push # the push url that will be used by users
    networks:
      - jcmcNet
    ports:
      - 3000:3000
      - 9229:9229 # Port for debugging
    volumes:
      - ".:/jcmc"
    working_dir: /jcmc
    command: sleep infinity

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - jcmcNet
    
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - jcmcNet
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3001:3000'
    networks:
      - jcmcNet
      
networks:
  jcmcNet:
    driver: bridge